export const committees = [
  {
    country: "Austria",
    lcs: ["Graz", "Innsbruck", "Leoben", "Linz", "Vienna"],
    page: "https://www.iaeste.at/en/",
  },
  {
    country: "Belgium",
    lcs: ["Brussels", "Leuven", "Ghent"],
    page: "https://iaeste.be/",
  },
  {
    country: "Bosnia-and-Herzegovina",
    lcs: ["Banja Luka", "Sarajevo", "Mostar"],
    page: "",
  },
  {
    country: "Croatia",
    lcs: ["Osijek", "Pula", "Rijeka", "Split", "Zagreb"],
    page: "https://www.iaeste.hr/",
  },
  {
    country: "Czech-Republic",
    lcs: [
      "Prague",
      "Brno",
      "Ostrava",
      "Pilsen",
      "Liberec",
      "Zlin",
      "Pardubice",
    ],
    page: "https://www.iaeste.cz/",
  },
  {
    country: "France",
    lcs: ["Grenoble"],
    page: "https://www.iaeste-france.fr/en/",
  },
  {
    country: "Germany",
    lcs: [
      "Aachen",
      "Bayreuth",
      "Berlin",
      "Bochum",
      "Bonn",
      "Brandenburg",
      "Bremen",
      "Chemnitz",
      "Cottbus",
      "Darmstadt",
      "Detmold",
      "Dortmund",
      "Dresden",
      "Emden/Leer",
      "Erlangen",
      "Frankfurt",
      "Freiberg",
      "Freiburg",
      "Freising",
      "Gießen",
      "Göttingen",
      "Greifswald",
      "Halle",
      "Hamburg",
      "Hannover",
      "Harz",
      "Heide",
      "Heidelberg",
      "Illmenau",
      "Jena",
      "Kaiserslautern",
      "Karlsruhe",
      "Kiel",
      "Köln",
      "Konstanz",
      "Leipzig",
      "Lübeck",
      "Lüneburg",
      "Main",
      "Merseburg",
      "München",
      "Oldenburg",
      "Osnabrück",
      "Paderborn",
      "Potsdam",
      "Rostock",
      "Saarbrücken",
      "Stuttgart",
      "Weimar",
      "Wismar",
      "Zittau",
    ],
    page: "https://www.iaeste.de/en/",
  },
  {
    country: "Hungary",
    lcs: ["Budapest", "Győr"],
    page: "https://iaeste.hu/",
  },
  {
    country: "Macedonia",
    lcs: ["Skopje", "Bitola", "Ohrid", "Stip"],
    page: "https://iaeste.org.mk/",
  },
  {
    country: "Malta",
    lcs: ["Msida"],
    page: "https://iaeste.org.mt/",
  },
  {
    country: "Norway",
    lcs: [
      "Bergen",
      "Grimstad",
      "Oslo",
      "Stavanger",
      "Tromsø",
      "Trondheim",
      "Ås",
    ],
    page: "https://www.iaeste.no/",
  },
  {
    country: "Poland",
    lcs: [
      "Warszawa",
      "Szczecin",
      "Krakow",
      "Lodz",
      "Wroclowe",
      "Gliwice",
      "Rzeszow",
      "Gdansk",
      "Poznan",
    ],
    page: "https://iaeste.pl/",
  },
  {
    country: "Slovakia",
    lcs: ["Bratislava", "Žilina", "Zvolen", "Košice"],
    page: "https://iaeste.sk/",
  },
  {
    country: "Slovenia",
    lcs: ["Ljubljana", "Maribor"],
    page: "http://iaeste.si/",
  },
  {
    country: "Spain",
    lcs: [
      "Madrid",
      "Bilbao",
      "Barcelona",
      "Zaragoza",
      "Lleida",
      "Valencia",
      "Sevilla",
      "Málaga",
      "Alicante",
      "Elche",
      "Aragón",
    ],
    page: "https://iaeste.es/",
  },
  {
    country: "Switzerland",
    lcs: ["Zurich", "Bern", "Basel", "Lausanne"],
    page: "https://www.iaeste.ch/en/",
  },
  {
    country: "Sweden",
    lcs: ["Luleå", "Stockholm", "Linköping", "Gothenburg", "Lund"],
    page: "https://iaeste.se/",
  },
  // {
  //   country: "Tunisia",
  //   lcs: ["Tunis"],
  //   page: "http://www.iaeste.tn/tunisia/",
  // },
  {
    country: "Turkiye",
    lcs: ["İstanbul", "Ankara", "Kocaeli", "İzmir"],
    page: "https://iaeste.org.tr/",
  },
];
